pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=continuous-integration/travis-ci/push
#      - status-success=Jenkins@VSP
      - "#approved-reviews-by>=0"
      - label=automerge
#      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: merge
        strict: true


